spring.application.name=auth-core-api

# Aqui você pode colocar qualquer palavra, senha ou hash.
# Em produção, isso seria uma variável de ambiente escondida no servidor.
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-muito-segura}
